# Generated by Django 5.1.2 on 2024-10-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_friendly_name_product_ku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ku',
            new_name='sku',
        ),
    ]
