# Generated by Django 5.1.2 on 2024-10-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_ku_product_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
