# Generated by Django 5.1.2 on 2024-11-01 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_image_alter_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildYourOwn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('custom_message', models.CharField(blank=True, max_length=200, null=True)),
                ('packaging_type', models.CharField(choices=[('standard', 'Standard'), ('gift', 'Gift Wrap')], default='standard', max_length=50)),
                ('add_ons', models.ManyToManyField(blank=True, related_name='as_add_on', to='products.product')),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_builds', to='products.product')),
            ],
        ),
    ]
