# Generated by Django 5.1.2 on 2024-11-02 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_buildyourown'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuildYourOwn',
        ),
    ]
