# Generated by Django 5.1.2 on 2024-12-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
